[package]
name = "hacker"
version = "0.5.0"
edition = "2021"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
colored = "2.1"
uuid = { version = "1.10", features = ["v4"] }
rand = "0.8.5"
